// Generated by Scripts/export-web-data.sh from Swift core. Do not edit manually.
export const GAME_DATA = {
  "allowedLetters" : [
    "А",
    "В",
    "Е",
    "К",
    "М",
    "Н",
    "О",
    "Р",
    "С",
    "Т",
    "У",
    "Х"
  ],
  "config" : {
    "baseHashDigitMultiplier" : 7,
    "baseHashLetterMultiplier" : 23,
    "baseHashRegionMultiplier" : 11,
    "basePriceRange" : [
      120,
      479
    ],
    "beautifulDigits" : [
      "001",
      "002",
      "003",
      "005",
      "007",
      "010",
      "011",
      "022",
      "033",
      "044",
      "055",
      "066",
      "077",
      "088",
      "099",
      "100",
      "200",
      "300",
      "500",
      "700",
      "770",
      "800",
      "900"
    ],
    "counterDuration" : 0.66,
    "finishingDuration" : 0.75,
    "generationAttempts" : 80,
    "initialBalance" : 1800000,
    "legendaryPause" : 0.45,
    "maximumCollectionCount" : 2000,
    "priceBands" : {
      "common" : {
        "maximum" : 10000,
        "minimum" : 50
      },
      "epic" : {
        "maximum" : 20000000,
        "minimum" : 5000000
      },
      "legendary" : {
        "maximum" : 75000000,
        "minimum" : 10000000
      },
      "rare" : {
        "maximum" : 7000000,
        "minimum" : 1000000
      },
      "uncommon" : {
        "maximum" : 1500000,
        "minimum" : 100000
      }
    },
    "rarityThresholds" : {
      "common" : 0,
      "epic" : 6.8,
      "legendary" : 9.1,
      "rare" : 4.2,
      "uncommon" : 1.6
    },
    "rarityWeights" : {
      "common" : 75,
      "epic" : 0.85,
      "legendary" : 0.15,
      "rare" : 5,
      "uncommon" : 19
    },
    "recordToastDuration" : 4.5,
    "recoveryCooldown" : 21600,
    "recoveryGrant" : 600000,
    "regionGenerationWeights" : {
      "04" : 0.3,
      "06" : 0.3,
      "16" : 3,
      "17" : 0.3,
      "23" : 3,
      "49" : 0.3,
      "50" : 4,
      "52" : 3,
      "77" : 6,
      "78" : 4,
      "79" : 0.3,
      "87" : 0.2,
      "97" : 3,
      "99" : 3,
      "116" : 2,
      "123" : 2,
      "150" : 3,
      "178" : 2,
      "198" : 2,
      "750" : 2,
      "777" : 3,
      "799" : 2,
      "977" : 2
    },
    "revealDurationBands" : {
      "common" : [
        1.2,
        2
      ],
      "epic" : [
        4,
        6.4
      ],
      "legendary" : [
        5,
        7.6
      ],
      "rare" : [
        3,
        5
      ],
      "uncommon" : [
        2,
        3.4
      ]
    },
    "revealMaximum" : 7.6,
    "revealMinimum" : 1.2,
    "rollCost" : 300000,
    "rollDuration" : 3.25,
    "rollPlateCount" : 24,
    "selectionPause" : 0.24,
    "sequences" : [
      "123",
      "234",
      "321",
      "345",
      "432",
      "456",
      "543",
      "567",
      "654",
      "678",
      "765",
      "789",
      "876",
      "987"
    ],
    "traitRevealInterval" : 0.88,
    "traitRules" : {
      "beautifulDigits" : {
        "flatBonus" : 60000,
        "priceMultiplier" : 2.5,
        "rarityWeight" : 1.5,
        "revealPriority" : 24
      },
      "doubleDigits" : {
        "flatBonus" : 0,
        "priceMultiplier" : 2,
        "rarityWeight" : 0.35,
        "revealPriority" : 30
      },
      "doubleLetters" : {
        "flatBonus" : 0,
        "priceMultiplier" : 2.2,
        "rarityWeight" : 0.8,
        "revealPriority" : 40
      },
      "iconicCombination.A001AA77" : {
        "flatBonus" : 8000000,
        "priceMultiplier" : 4.4,
        "rarityWeight" : 3.1,
        "revealPriority" : 80
      },
      "iconicCombination.A770OO77" : {
        "flatBonus" : 0,
        "priceMultiplier" : 3.1,
        "rarityWeight" : 3.1,
        "revealPriority" : 80
      },
      "iconicCombination.E222EE52" : {
        "flatBonus" : 0,
        "priceMultiplier" : 6.7,
        "rarityWeight" : 3.1,
        "revealPriority" : 80
      },
      "iconicCombination.O777OO77" : {
        "flatBonus" : 5000000,
        "priceMultiplier" : 2.1,
        "rarityWeight" : 3.1,
        "revealPriority" : 80
      },
      "mirrorDigits" : {
        "flatBonus" : 0,
        "priceMultiplier" : 3.2,
        "rarityWeight" : 0.7,
        "revealPriority" : 20
      },
      "rareRegion" : {
        "flatBonus" : 20000,
        "priceMultiplier" : 1.35,
        "rarityWeight" : 1,
        "revealPriority" : 58
      },
      "regionMatch" : {
        "flatBonus" : 2500000,
        "priceMultiplier" : 2,
        "rarityWeight" : 2,
        "revealPriority" : 55
      },
      "repeatedRegion" : {
        "flatBonus" : 0,
        "priceMultiplier" : 1.3,
        "rarityWeight" : 0.4,
        "revealPriority" : 50
      },
      "sequenceDigits" : {
        "flatBonus" : 15000,
        "priceMultiplier" : 7,
        "rarityWeight" : 1.6,
        "revealPriority" : 22
      },
      "seriesResonance" : {
        "flatBonus" : 4000000,
        "priceMultiplier" : 5,
        "rarityWeight" : 0.15,
        "revealPriority" : 70
      },
      "specialSeries.collectible" : {
        "flatBonus" : 450000,
        "priceMultiplier" : 2,
        "rarityWeight" : 1.4,
        "revealPriority" : 60
      },
      "specialSeries.eee" : {
        "flatBonus" : 1500000,
        "priceMultiplier" : 3,
        "rarityWeight" : 1.8,
        "revealPriority" : 60
      },
      "specialSeries.heritage" : {
        "flatBonus" : 1500000,
        "priceMultiplier" : 3,
        "rarityWeight" : 1.8,
        "revealPriority" : 60
      },
      "specialSeries.official" : {
        "flatBonus" : 1500000,
        "priceMultiplier" : 4,
        "rarityWeight" : 2.2,
        "revealPriority" : 60
      },
      "tripleDigits" : {
        "flatBonus" : 0,
        "priceMultiplier" : 40,
        "rarityWeight" : 2.9,
        "revealPriority" : 20
      },
      "tripleLetters" : {
        "flatBonus" : 0,
        "priceMultiplier" : 30,
        "rarityWeight" : 2.7,
        "revealPriority" : 40
      },
      "visualMatch" : {
        "flatBonus" : 100000,
        "priceMultiplier" : 1.8,
        "rarityWeight" : 0.9,
        "revealPriority" : 45
      }
    },
    "variationRange" : [
      0.92,
      1.08
    ]
  },
  "rarities" : [
    {
      "color" : "#A8B3C4",
      "key" : "common",
      "label" : "Обычный",
      "rank" : 0
    },
    {
      "color" : "#5ECC99",
      "key" : "uncommon",
      "label" : "Необычный",
      "rank" : 1
    },
    {
      "color" : "#5296EB",
      "key" : "rare",
      "label" : "Редкий",
      "rank" : 2
    },
    {
      "color" : "#A86EED",
      "key" : "epic",
      "label" : "Эпический",
      "rank" : 3
    },
    {
      "color" : "#F5B852",
      "key" : "legendary",
      "label" : "Легендарный",
      "rank" : 4
    }
  ],
  "referenceFixtures" : [
    {
      "basePrice" : 224,
      "finalPrice" : 15452880,
      "id" : "00000000-0000-0000-0000-000000000001",
      "obtainedAt" : "1970-01-01T00:00:00Z",
      "plate" : {
        "digits" : "222",
        "letters" : "ЕЕЕ",
        "region" : {
          "code" : "52",
          "generationWeight" : 1,
          "isRare" : false,
          "name" : "Нижегородская область",
          "valuationMultiplier" : 1
        },
        "type" : "standard"
      },
      "rarity" : "legendary",
      "traits" : [
        {
          "description" : "Тройное повторение 222 — узнаваемая цифровая комбинация.",
          "flatBonus" : 0,
          "id" : "tripleDigits",
          "name" : "3 одинаковые цифры",
          "priceMultiplier" : 40,
          "rarityWeight" : 2.9,
          "revealPriority" : 20
        },
        {
          "description" : "Все буквы серии ЕЕЕ совпадают.",
          "flatBonus" : 0,
          "id" : "tripleLetters",
          "name" : "3 одинаковые буквы",
          "priceMultiplier" : 30,
          "rarityWeight" : 2.7,
          "revealPriority" : 40
        },
        {
          "description" : "Игровая историческая ассоциация серии ЕЕЕ с таможенной тематикой. Не является утверждением о владельце конкретного автомобиля.",
          "flatBonus" : 1500000,
          "id" : "specialSeries",
          "name" : "Таможня",
          "priceMultiplier" : 3,
          "rarityWeight" : 1.8,
          "revealPriority" : 60
        },
        {
          "description" : "Е 222 ЕЕ · 52 — редкое сочетание серии, цифр и региона в игровом каталоге.",
          "flatBonus" : 0,
          "id" : "iconicCombination",
          "name" : "Знаковая комбинация",
          "priceMultiplier" : 6.7,
          "rarityWeight" : 3.1,
          "revealPriority" : 80
        }
      ],
      "valuationSteps" : [
        {
          "price" : 224,
          "rarity" : "common",
          "trait" : null
        },
        {
          "price" : 100000,
          "rarity" : "uncommon",
          "trait" : {
            "description" : "Тройное повторение 222 — узнаваемая цифровая комбинация.",
            "flatBonus" : 0,
            "id" : "tripleDigits",
            "name" : "3 одинаковые цифры",
            "priceMultiplier" : 40,
            "rarityWeight" : 2.9,
            "revealPriority" : 20
          }
        },
        {
          "price" : 1000000,
          "rarity" : "rare",
          "trait" : {
            "description" : "Все буквы серии ЕЕЕ совпадают.",
            "flatBonus" : 0,
            "id" : "tripleLetters",
            "name" : "3 одинаковые буквы",
            "priceMultiplier" : 30,
            "rarityWeight" : 2.7,
            "revealPriority" : 40
          }
        },
        {
          "price" : 5000000,
          "rarity" : "epic",
          "trait" : {
            "description" : "Игровая историческая ассоциация серии ЕЕЕ с таможенной тематикой. Не является утверждением о владельце конкретного автомобиля.",
            "flatBonus" : 1500000,
            "id" : "specialSeries",
            "name" : "Таможня",
            "priceMultiplier" : 3,
            "rarityWeight" : 1.8,
            "revealPriority" : 60
          }
        },
        {
          "price" : 15452880,
          "rarity" : "legendary",
          "trait" : {
            "description" : "Е 222 ЕЕ · 52 — редкое сочетание серии, цифр и региона в игровом каталоге.",
            "flatBonus" : 0,
            "id" : "iconicCombination",
            "name" : "Знаковая комбинация",
            "priceMultiplier" : 6.7,
            "rarityWeight" : 3.1,
            "revealPriority" : 80
          }
        }
      ],
      "variationFactor" : 1
    },
    {
      "basePrice" : 153,
      "finalPrice" : 44215620,
      "id" : "00000000-0000-0000-0000-000000000002",
      "obtainedAt" : "1970-01-01T00:00:00Z",
      "plate" : {
        "digits" : "770",
        "letters" : "АОО",
        "region" : {
          "code" : "77",
          "generationWeight" : 1,
          "isRare" : false,
          "name" : "Москва",
          "valuationMultiplier" : 1
        },
        "type" : "standard"
      },
      "rarity" : "legendary",
      "traits" : [
        {
          "description" : "Коллекционная цифровая комбинация из игрового справочника.",
          "flatBonus" : 60000,
          "id" : "beautifulDigits",
          "name" : "Красивая комбинация 770",
          "priceMultiplier" : 2.5,
          "rarityWeight" : 1.5,
          "revealPriority" : 24
        },
        {
          "description" : "Две цифры в комбинации 770 совпадают.",
          "flatBonus" : 0,
          "id" : "doubleDigits",
          "name" : "2 одинаковые цифры",
          "priceMultiplier" : 2,
          "rarityWeight" : 0.35,
          "revealPriority" : 30
        },
        {
          "description" : "Две буквы серии АОО совпадают.",
          "flatBonus" : 0,
          "id" : "doubleLetters",
          "name" : "2 одинаковые буквы",
          "priceMultiplier" : 2.2,
          "rarityWeight" : 0.8,
          "revealPriority" : 40
        },
        {
          "description" : "Код региона 77 состоит из одинаковых цифр.",
          "flatBonus" : 0,
          "id" : "repeatedRegion",
          "name" : "Одинаковые цифры региона",
          "priceMultiplier" : 1.3,
          "rarityWeight" : 0.4,
          "revealPriority" : 50
        },
        {
          "description" : "Комбинация 770 повторяет код 77 в начале, конце или без ведущего нуля.",
          "flatBonus" : 2500000,
          "id" : "regionMatch",
          "name" : "Цифры совпадают с регионом",
          "priceMultiplier" : 2,
          "rarityWeight" : 2,
          "revealPriority" : 55
        },
        {
          "description" : "Игровая историческая ассоциация серии АОО с автомобилями управления делами Президента. Не определяет владельца конкретного автомобиля.",
          "flatBonus" : 1500000,
          "id" : "specialSeries",
          "name" : "Управление делами Президента",
          "priceMultiplier" : 4,
          "rarityWeight" : 2.2,
          "revealPriority" : 60
        },
        {
          "description" : "А 770 ОО · 77 — редкое сочетание серии, цифр и региона в игровом каталоге.",
          "flatBonus" : 0,
          "id" : "iconicCombination",
          "name" : "Знаковая комбинация",
          "priceMultiplier" : 3.1,
          "rarityWeight" : 3.1,
          "revealPriority" : 80
        }
      ],
      "valuationSteps" : [
        {
          "price" : 153,
          "rarity" : "common",
          "trait" : null
        },
        {
          "price" : 10000,
          "rarity" : "common",
          "trait" : {
            "description" : "Коллекционная цифровая комбинация из игрового справочника.",
            "flatBonus" : 60000,
            "id" : "beautifulDigits",
            "name" : "Красивая комбинация 770",
            "priceMultiplier" : 2.5,
            "rarityWeight" : 1.5,
            "revealPriority" : 24
          }
        },
        {
          "price" : 120765,
          "rarity" : "uncommon",
          "trait" : {
            "description" : "Две цифры в комбинации 770 совпадают.",
            "flatBonus" : 0,
            "id" : "doubleDigits",
            "name" : "2 одинаковые цифры",
            "priceMultiplier" : 2,
            "rarityWeight" : 0.35,
            "revealPriority" : 30
          }
        },
        {
          "price" : 265683,
          "rarity" : "uncommon",
          "trait" : {
            "description" : "Две буквы серии АОО совпадают.",
            "flatBonus" : 0,
            "id" : "doubleLetters",
            "name" : "2 одинаковые буквы",
            "priceMultiplier" : 2.2,
            "rarityWeight" : 0.8,
            "revealPriority" : 40
          }
        },
        {
          "price" : 345388,
          "rarity" : "uncommon",
          "trait" : {
            "description" : "Код региона 77 состоит из одинаковых цифр.",
            "flatBonus" : 0,
            "id" : "repeatedRegion",
            "name" : "Одинаковые цифры региона",
            "priceMultiplier" : 1.3,
            "rarityWeight" : 0.4,
            "revealPriority" : 50
          }
        },
        {
          "price" : 3190776,
          "rarity" : "rare",
          "trait" : {
            "description" : "Комбинация 770 повторяет код 77 в начале, конце или без ведущего нуля.",
            "flatBonus" : 2500000,
            "id" : "regionMatch",
            "name" : "Цифры совпадают с регионом",
            "priceMultiplier" : 2,
            "rarityWeight" : 2,
            "revealPriority" : 55
          }
        },
        {
          "price" : 14263103,
          "rarity" : "epic",
          "trait" : {
            "description" : "Игровая историческая ассоциация серии АОО с автомобилями управления делами Президента. Не определяет владельца конкретного автомобиля.",
            "flatBonus" : 1500000,
            "id" : "specialSeries",
            "name" : "Управление делами Президента",
            "priceMultiplier" : 4,
            "rarityWeight" : 2.2,
            "revealPriority" : 60
          }
        },
        {
          "price" : 44215620,
          "rarity" : "legendary",
          "trait" : {
            "description" : "А 770 ОО · 77 — редкое сочетание серии, цифр и региона в игровом каталоге.",
            "flatBonus" : 0,
            "id" : "iconicCombination",
            "name" : "Знаковая комбинация",
            "priceMultiplier" : 3.1,
            "rarityWeight" : 3.1,
            "revealPriority" : 80
          }
        }
      ],
      "variationFactor" : 1
    }
  ],
  "regions" : [
    {
      "code" : "01",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Республика Адыгея",
      "valuationMultiplier" : 1
    },
    {
      "code" : "02",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Республика Башкортостан",
      "valuationMultiplier" : 1
    },
    {
      "code" : "03",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Республика Бурятия",
      "valuationMultiplier" : 1
    },
    {
      "code" : "04",
      "generationWeight" : 1,
      "isRare" : true,
      "name" : "Республика Алтай",
      "valuationMultiplier" : 1
    },
    {
      "code" : "05",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Республика Дагестан",
      "valuationMultiplier" : 1
    },
    {
      "code" : "06",
      "generationWeight" : 1,
      "isRare" : true,
      "name" : "Республика Ингушетия",
      "valuationMultiplier" : 1
    },
    {
      "code" : "07",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Кабардино-Балкарская Республика",
      "valuationMultiplier" : 1
    },
    {
      "code" : "08",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Республика Калмыкия",
      "valuationMultiplier" : 1
    },
    {
      "code" : "09",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Карачаево-Черкесская Республика",
      "valuationMultiplier" : 1
    },
    {
      "code" : "10",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Республика Карелия",
      "valuationMultiplier" : 1
    },
    {
      "code" : "11",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Республика Коми",
      "valuationMultiplier" : 1
    },
    {
      "code" : "12",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Республика Марий Эл",
      "valuationMultiplier" : 1
    },
    {
      "code" : "13",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Республика Мордовия",
      "valuationMultiplier" : 1
    },
    {
      "code" : "14",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Республика Саха (Якутия)",
      "valuationMultiplier" : 1
    },
    {
      "code" : "15",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Республика Северная Осетия — Алания",
      "valuationMultiplier" : 1
    },
    {
      "code" : "16",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Республика Татарстан",
      "valuationMultiplier" : 1
    },
    {
      "code" : "17",
      "generationWeight" : 1,
      "isRare" : true,
      "name" : "Республика Тыва",
      "valuationMultiplier" : 1
    },
    {
      "code" : "18",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Удмуртская Республика",
      "valuationMultiplier" : 1
    },
    {
      "code" : "19",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Республика Хакасия",
      "valuationMultiplier" : 1
    },
    {
      "code" : "21",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Чувашская Республика",
      "valuationMultiplier" : 1
    },
    {
      "code" : "22",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Алтайский край",
      "valuationMultiplier" : 1
    },
    {
      "code" : "23",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Краснодарский край",
      "valuationMultiplier" : 1
    },
    {
      "code" : "24",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Красноярский край",
      "valuationMultiplier" : 1
    },
    {
      "code" : "25",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Приморский край",
      "valuationMultiplier" : 1
    },
    {
      "code" : "26",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Ставропольский край",
      "valuationMultiplier" : 1
    },
    {
      "code" : "27",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Хабаровский край",
      "valuationMultiplier" : 1
    },
    {
      "code" : "28",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Амурская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "29",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Архангельская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "30",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Астраханская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "31",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Белгородская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "32",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Брянская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "33",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Владимирская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "34",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Волгоградская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "35",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Вологодская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "36",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Воронежская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "37",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Ивановская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "38",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Иркутская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "39",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Калининградская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "40",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Калужская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "41",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Камчатский край",
      "valuationMultiplier" : 1
    },
    {
      "code" : "42",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Кемеровская область — Кузбасс",
      "valuationMultiplier" : 1
    },
    {
      "code" : "43",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Кировская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "44",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Костромская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "45",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Курганская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "46",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Курская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "47",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Ленинградская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "48",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Липецкая область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "49",
      "generationWeight" : 1,
      "isRare" : true,
      "name" : "Магаданская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "50",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Московская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "51",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Мурманская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "52",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Нижегородская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "53",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Новгородская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "54",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Новосибирская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "55",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Омская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "56",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Оренбургская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "57",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Орловская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "58",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Пензенская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "59",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Пермский край",
      "valuationMultiplier" : 1
    },
    {
      "code" : "60",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Псковская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "61",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Ростовская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "62",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Рязанская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "63",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Самарская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "64",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Саратовская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "65",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Сахалинская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "66",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Свердловская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "67",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Смоленская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "68",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Тамбовская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "69",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Тверская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "70",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Томская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "71",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Тульская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "72",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Тюменская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "73",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Ульяновская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "74",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Челябинская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "75",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Забайкальский край",
      "valuationMultiplier" : 1
    },
    {
      "code" : "76",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Ярославская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "77",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Москва",
      "valuationMultiplier" : 1
    },
    {
      "code" : "78",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Санкт-Петербург",
      "valuationMultiplier" : 1
    },
    {
      "code" : "79",
      "generationWeight" : 1,
      "isRare" : true,
      "name" : "Еврейская автономная область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "82",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Республика Крым",
      "valuationMultiplier" : 1
    },
    {
      "code" : "83",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Ненецкий автономный округ",
      "valuationMultiplier" : 1
    },
    {
      "code" : "86",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Ханты-Мансийский автономный округ — Югра",
      "valuationMultiplier" : 1
    },
    {
      "code" : "87",
      "generationWeight" : 1,
      "isRare" : true,
      "name" : "Чукотский автономный округ",
      "valuationMultiplier" : 1
    },
    {
      "code" : "89",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Ямало-Ненецкий автономный округ",
      "valuationMultiplier" : 1
    },
    {
      "code" : "90",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Московская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "91",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Калининградская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "92",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Севастополь",
      "valuationMultiplier" : 1
    },
    {
      "code" : "93",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Краснодарский край",
      "valuationMultiplier" : 1
    },
    {
      "code" : "94",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Байконур",
      "valuationMultiplier" : 1
    },
    {
      "code" : "95",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Чеченская Республика",
      "valuationMultiplier" : 1
    },
    {
      "code" : "96",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Свердловская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "97",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Москва",
      "valuationMultiplier" : 1
    },
    {
      "code" : "98",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Санкт-Петербург",
      "valuationMultiplier" : 1
    },
    {
      "code" : "99",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Москва",
      "valuationMultiplier" : 1
    },
    {
      "code" : "102",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Республика Башкортостан",
      "valuationMultiplier" : 1
    },
    {
      "code" : "103",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Республика Бурятия",
      "valuationMultiplier" : 1
    },
    {
      "code" : "113",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Республика Мордовия",
      "valuationMultiplier" : 1
    },
    {
      "code" : "116",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Республика Татарстан",
      "valuationMultiplier" : 1
    },
    {
      "code" : "118",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Удмуртская Республика",
      "valuationMultiplier" : 1
    },
    {
      "code" : "121",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Чувашская Республика",
      "valuationMultiplier" : 1
    },
    {
      "code" : "122",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Алтайский край",
      "valuationMultiplier" : 1
    },
    {
      "code" : "123",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Краснодарский край",
      "valuationMultiplier" : 1
    },
    {
      "code" : "124",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Красноярский край",
      "valuationMultiplier" : 1
    },
    {
      "code" : "125",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Приморский край",
      "valuationMultiplier" : 1
    },
    {
      "code" : "126",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Ставропольский край",
      "valuationMultiplier" : 1
    },
    {
      "code" : "127",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Хабаровский край",
      "valuationMultiplier" : 1
    },
    {
      "code" : "134",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Волгоградская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "136",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Воронежская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "138",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Иркутская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "142",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Кемеровская область — Кузбасс",
      "valuationMultiplier" : 1
    },
    {
      "code" : "147",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Ленинградская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "150",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Московская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "152",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Нижегородская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "154",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Новосибирская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "155",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Омская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "156",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Оренбургская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "159",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Пермский край",
      "valuationMultiplier" : 1
    },
    {
      "code" : "161",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Ростовская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "163",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Самарская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "164",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Саратовская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "167",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Смоленская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "173",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Ульяновская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "174",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Челябинская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "177",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Москва",
      "valuationMultiplier" : 1
    },
    {
      "code" : "178",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Санкт-Петербург",
      "valuationMultiplier" : 1
    },
    {
      "code" : "186",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Ханты-Мансийский автономный округ — Югра",
      "valuationMultiplier" : 1
    },
    {
      "code" : "190",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Московская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "193",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Краснодарский край",
      "valuationMultiplier" : 1
    },
    {
      "code" : "196",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Свердловская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "197",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Москва",
      "valuationMultiplier" : 1
    },
    {
      "code" : "198",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Санкт-Петербург",
      "valuationMultiplier" : 1
    },
    {
      "code" : "199",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Москва",
      "valuationMultiplier" : 1
    },
    {
      "code" : "702",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Республика Башкортостан",
      "valuationMultiplier" : 1
    },
    {
      "code" : "716",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Республика Татарстан",
      "valuationMultiplier" : 1
    },
    {
      "code" : "750",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Московская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "761",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Ростовская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "763",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Самарская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "774",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Челябинская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "777",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Москва",
      "valuationMultiplier" : 1
    },
    {
      "code" : "790",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Московская область",
      "valuationMultiplier" : 1
    },
    {
      "code" : "797",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Москва",
      "valuationMultiplier" : 1
    },
    {
      "code" : "799",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Москва",
      "valuationMultiplier" : 1
    },
    {
      "code" : "977",
      "generationWeight" : 1,
      "isRare" : false,
      "name" : "Москва",
      "valuationMultiplier" : 1
    }
  ],
  "specialSeries" : [
    {
      "description" : "Игровая историческая ассоциация серии АОО с автомобилями управления делами Президента. Не определяет владельца конкретного автомобиля.",
      "id" : "aoo",
      "letters" : "АОО",
      "name" : "Управление делами Президента",
      "profile" : "official"
    },
    {
      "description" : "В игровом справочнике МОО связана с представительским автопарком и административной историей серии.",
      "id" : "moo",
      "letters" : "МОО",
      "name" : "Представительская серия",
      "profile" : "official"
    },
    {
      "description" : "Игровая историческая ассоциация ВОО с административным автопарком. Реальная принадлежность автомобиля по серии не устанавливается.",
      "id" : "boo",
      "letters" : "ВОО",
      "name" : "Административная серия",
      "profile" : "official"
    },
    {
      "description" : "СОО — коллекционная игровая ассоциация с автопарками особого назначения.",
      "id" : "coo",
      "letters" : "СОО",
      "name" : "Серия особого назначения",
      "profile" : "official"
    },
    {
      "description" : "Историческая ассоциация АМР с федеральными ведомствами используется исключительно как игровая характеристика.",
      "id" : "amr",
      "letters" : "АМР",
      "name" : "Федеральная серия",
      "profile" : "official"
    },
    {
      "description" : "ЕКХ — игровая историческая ассоциация с охранным автопарком. Серия не подтверждает статус автомобиля.",
      "id" : "ekx",
      "letters" : "ЕКХ",
      "name" : "Охранная серия",
      "profile" : "official"
    },
    {
      "description" : "Три буквы А — узнаваемая коллекционная серия с эффектом первого номера в алфавите.",
      "id" : "aaa",
      "letters" : "ААА",
      "name" : "Первая буква",
      "profile" : "collectible"
    },
    {
      "description" : "Симметричная серия ООО ценится в игровой коллекции за три одинаковых круглых символа.",
      "id" : "ooo",
      "letters" : "ООО",
      "name" : "Три кольца",
      "profile" : "collectible"
    },
    {
      "description" : "Серия МММ — выразительная коллекционная комбинация повторяющихся букв.",
      "id" : "mmm",
      "letters" : "МММ",
      "name" : "Тройная М",
      "profile" : "collectible"
    },
    {
      "description" : "ССС в игровом справочнике имеет историческую ведомственную ассоциацию. Не указывает на реального владельца.",
      "id" : "ccc",
      "letters" : "ССС",
      "name" : "Историческая серия ССС",
      "profile" : "heritage"
    },
    {
      "description" : "Три буквы К образуют запоминающуюся коллекционную серию.",
      "id" : "kkk",
      "letters" : "ККК",
      "name" : "Тройная К",
      "profile" : "collectible"
    },
    {
      "description" : "ХХХ — визуально симметричная коллекционная серия в игровом каталоге.",
      "id" : "xxx",
      "letters" : "ХХХ",
      "name" : "Тройной крест",
      "profile" : "collectible"
    },
    {
      "description" : "Игровая историческая ассоциация серии ЕЕЕ с таможенной тематикой. Не является утверждением о владельце конкретного автомобиля.",
      "id" : "eee",
      "letters" : "ЕЕЕ",
      "name" : "Таможня",
      "profile" : "heritage"
    }
  ]
};
